name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest
    name: Check source code formatting
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew :sdk:checkFormat :examples:checkFormat --continue

  test:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.Java }}
    strategy:
      matrix:
        java: [ '11', '17', '21', '25' ]

    steps:
      - uses: actions/checkout@v4
        # Gradle will detect the JVM installation from the ubuntu-latest image and use it
        # includes execution of unit tests
      - run: ./gradlew build -PjavaVersion=${{ matrix.java }} --stacktrace
